<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Support</title>
    <script src="http://code.jquery.com/jquery-3.3.1.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Exo+2|Fira+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../css/bootstrap.css">
    <link rel="stylesheet" href="../css/bootstrap-grid.css">
    <link rel="stylesheet" href="../css/bootstrap-reboot.css">
    <link rel="stylesheet" href="../css/extra-styles.css">
    <script src="../js/bootstrap.bundle.js"></script>
    <script src="../js/bootstrap.js"></script>
</head>
<body style="font-family: 'Fira Sans', sans-serif;">
<div class="wrapper" style="background-color: white">
    <div class="content">
        <div class="container">
            <div class="row mt-5" >
                <div class="col-3">
                </div>
                <div class="col-6 mt-3 align-content-center">
                    <h1>Technical support</h1>
                </div>
                <div class="col-3">
                </div>
            </div>
            <div class="row" >
                <div class="col-3">
                </div>
                <div class="col-6 mt-3 align-content-center">
                    <h4>You can contact us:</h4>
                </div>
                <div class="col-3">
                </div>
            </div>
            <div class="row mt-3" >
                <div class="col-3">
                </div>
                <div class="col-6 mt-3 align-content-center">
                    <h5>Mail:</h5> <a href="mailto:winsapptechnical@gmail.com">winsapptechnical@gmail.com</a>
                </div>
                <div class="col-3">
                </div>
            </div>
            <div class="row mt-3" >
                <div class="col-3">
                </div>
                <div class="col-6 mt-3 align-content-center">
                    <h5>Telegram:</h5> <a href="">@wins_app</a>
                </div>
                <div class="col-3">
                </div>
            </div>
        </div>
    </div>
    <div class="footer mb-3" style="bottom: 0; width: 100%;">
        <footer>
            <div class="row" >
                <div class="col-5">
                </div>
                <div class="col-2 align-content-center">
                    <a href="../privacy_policy.html">Privacy policy</a>
                </div>
                <div class="col-5">
                </div>
            </div>
        </footer>
    </div>
</div>
</body>
</html>